# Generated by Django 4.2.30 on 2026-08-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_abnormal_issue_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abnormalissue',
            options={'ordering': ['status', '-answer__record__inspection_date', '-created_at'], 'verbose_name': '異常対応', 'verbose_name_plural': '異常対応'},
        ),
    ]
